apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-storage
  resources:
    requests:
      storage: 5Gi
  volumeName: efs-postgres-pv
