apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-storage

provisioner: efs.csi.aws.com # Amazon EBS CSI driver
volumeBindingMode: WaitForFirstConsumer
# parameters:
#   type: gp3   
#   fsType: ext4
# parameters:
#   type: gp2
#   encrypted: 'true' # EFS volumes will always be encrypted by default
# volumeBindingMode: WaitForFirstConsumer
# reclaimPolicy: Delete
# mountOptions:
# - debug
